### ISSUE TITLE
Custom default values for subs

### ISSUE THREAD

**Issue by Suika** [thatfuckingbird/hydownloader#14]
SQLite does not really support retwriting the DDL, so the only option to change the default vaule for the initial, regular and abort after values is to edit the database directly, which is not optimal.
Do add default values globally or for specific sites. `subs.abort_after.default = 666`, `subs.abort_after.gelbooru = 20`, etc. Also, probably should be possible to send these default via API with the sub/url to be downloaded via HC.

**Comment by thatfuckingbird** [comment]
implemented in 0.4.0
