### ISSUE TITLE
Pixiv Site Test Fails Because Tested Work Has Been Deleted

### ISSUE THREAD

**Issue by GoAwayNow** [thatfuckingbird/hydownloader#24]
![2022-05-14 (1)](https://user-images.githubusercontent.com/56808771/168455582-28b7349f-58a1-4d61-b194-8ac3ad3be1bd.png)
When I noticed that the manga test failed outright despite the ugoira test working (the fails there are due to my config choices), I checked [the work being downloaded in the first test](https://www.pixiv.net/en/artworks/94515594). It was deleted at some point, causing the test to fail incorrectly.

**Comment by thatfuckingbird** [comment]
fixed
