### ISSUE TITLE
Default hentaifoundry import job fails on stories

### ISSUE THREAD

**Issue by hyuugi** [thatfuckingbird/hydownloader#31]
Hentaifoundry artists can upload text-based work to their profiles. These stories will get downloaded as part of a regular artist subscription.

When importing a hentaifoundry artist into hydrus the default import job will fail.

Fails on 'media' json_data. The 'media' element is not created for stories.
Fails on 'tags' json_data. There may not be any tags associated with a story.

**Comment by thatfuckingbird** [comment]
thanks, merged your fix
