### ISSUE TITLE
Can't add Artstation likes as a subscription

### ISSUE THREAD

**Issue by sbstratos79** [thatfuckingbird/hydownloader#34]
I can download Artstation likes from a profile with "Single URL queue" feature without any issues. But adding it as a subscription doesn't work. I get this error:
`No suitable extractor found for 'https://www.artstation.com/sbstratos79/likes'`
I am using `sbstratos79/likes` as the keyword.

**Comment by thatfuckingbird** [comment]
This message comes from gallery-dl, basically it does not recognize this URL format. Interestingly, if I simply call gallery-dl from the command line with that URL it works, so something doesn't add up here.
Which downloader are you using for that subscription? The `artstationuser` one is specifically meant for a user's entire gallery, not likes. The `raw` downloader is suited for these cases, that just passes the entire `keyword` field to gallery-dl as a URL.
Try with `raw` and set keywords to the full URL to your likes page. Does that work?

**Comment by thatfuckingbird** [comment]
Although with your keyword the artstationuser one should still work I think(?). Can you upload the full log txt file for this non-working sub?

**Comment by sbstratos79** [comment]
> Although with your keyword the artstationuser one should still work I think(?). Can you upload the full log txt file for this non-working sub?

Uh... I added the subscription again, and now it's working.. I think the `L` in `links` was capitalized when I tried earlier. Sorry for the false report.
