### ISSUE TITLE
Set the file publish date as the modified date

### ISSUE THREAD

**Issue by sbstratos79** [thatfuckingbird/hydownloader#35]
Currently, all the files that I export from hydownloader to Hydrus have the same `imported` and `modified` dates. If I use Hydrus' internal downloader, it correctly sets the `modified date` as the date the image was published on.
hydownloader import:
![mpv-shot0001](https://user-images.githubusercontent.com/4395586/199698134-c13923b6-41c7-43e3-81e8-94b931208af7.png)

Hydrus import:
![mpv-shot0002](https://user-images.githubusercontent.com/4395586/199698195-87bea47f-d735-41d2-8ea4-cf64c2d1aa05.png)

**Comment by thatfuckingbird** [comment]
Try setting usePathBasedImport to true in the import jobs json. That way the importer will send the file paths not the file contents to Hydrus, so Hydrus will see the modification time of the files on the filesystem (which gallery-dl should set correctly).
This probably needs to be documented.

**Comment by sbstratos79** [comment]
I am reopening this issue because the problem still persists with artstation images. The modified time associated with __most__ artstation images is the download time. The reason I said "most" is because some artstation images do infact display the correct modified time. A lot of those files are `gif` but some are `jpg` as well. So I can't figure out the pattern. Booru images display the correct modified time however.

**Comment by thatfuckingbird** [comment]
That sounds like a gallery-dl problem (if the times are wrong on the filesystem too before import, not just in Hydrus).
Looking at the docs https://github.com/mikf/gallery-dl/blob/master/docs/configuration.rst I dont see any artstation-specific options that could affect this. My guess is that gallery-dl fails to parse the published datetime in these cases, which, if true, should be reported there.

**Comment by sbstratos79** [comment]
It does seem to be a problem with gallery-dl. I manually downloaded an artstation gallery with gallery-dl and got incorrect modified times. And yes, modified times are incorrect in the filesystem, even before importing.
I will report this issue in gallery-dl repo. Thanks.

**Comment by sbstratos79** [comment]
Adding 'mtime' post processor under `artstation` in gallery-dl user config fixes this issue. You can check the linked issue for more details. 
I think this should be made a default option for the gallery-dl config generated by hydownloader. At least until this gets patched in gallery-dl.
This is what the artstation entry in my user config looks like:
```"artstation":
        {
            "external": false,
            "postprocessors": [{
                "name": "mtime"
            }]
        }

**Comment by thatfuckingbird** [comment]
Nice. I will add it to the defaults.

**Comment by thatfuckingbird** [comment]
Thinking about if maybe it would be better to add it globally for all sites not just artstation, but not all sites might use the `date` field (which is the default for mtime). So maybe its safer to keep it to just artstation now.

**Comment by sbstratos79** [comment]
> Thinking about if maybe it would be better to add it globally for all sites not just artstation, but not all sites might use the `date` field (which is the default for mtime). So maybe its safer to keep it to just artstation now.

The few sources I tested with hydownloader seemed to be applying the correct modified dates to the files, with the exception of Artstation. So yeah, I think keeping this change limited to artstation is the way to go, for now.
