### ISSUE TITLE
Tag with ':' errors out

### ISSUE THREAD

**Issue by sbstratos79** [thatfuckingbird/hydownloader#36]
Hope this gets fixed.
```
Processing file: gallery-dl/artstation/sbstratos79/Likes/artstation_2762699_9372602_push the button.jpg...
Error: the rule named artstation generated tags yielded a tag ending with ':' (creator:WELTOL :)

**Comment by thatfuckingbird** [comment]
If this tag is indeed correct, you can disable this check with the allowTagsEndingWithColon option.

**Comment by sbstratos79** [comment]
> If this tag is indeed correct, you can disable this check with the allowTagsEndingWithColon option.

Thanks!
