### ISSUE TITLE
Allow non-local connections

### ISSUE THREAD

**Issue by sbstratos79** [thatfuckingbird/hydownloader#37]
Hydrus has this option for the client api. I'm unable to connect with the api from my phone. I looked through the docs and couldn't find any relevant option. 
![Screenshot from 2022-11-07 16-41-12](https://user-images.githubusercontent.com/4395586/200297824-e954b23f-5dbc-4917-96dc-88f78ea46d6c.png)

**Comment by thatfuckingbird** [comment]
How is this related to hydownloader?

**Comment by sbstratos79** [comment]
Nvm. I tried using my pc's ip address as `daemon.host` value but I foolishly added `http` at the front. It works without `http`.
