### ISSUE TITLE
Imported entries are not added to import database

### ISSUE THREAD

**Issue by Suika** [thatfuckingbird/hydownloader#8]
```
Hashing...
File is already in Hydrus
Associating URLs...
Adding tags...
Writing entry to import database...
```
and no entry is written to the database.
Do write the entries on every entry being processed, because if the porcess fails a few hundred ot thousend entried into the import, it will have to restart from the beginning

**Comment by thatfuckingbird** [comment]
done in 20b088cd444c6ebdd3d46d8f4c9de9e51ca7d1c6
